name:                fraktell
version:             0.1.0.0
github:              "rileyweber13/fraktell"
license:             MIT
author:              "Riley Weber"
maintainer:          "rileyw13@protonmail.com"
copyright:           "2019 Riley Weber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Visualiztion of fractals
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rileyweber13/fraktell#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  fraktell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fraktell

tests:
  fraktell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fraktell
